version: "3"
services:
  server:
    image: zalgo
    build: .
    #command: python3 ZalgoBot.py
    ports:
      - 8000:8000
    networks:
      - zalgo_net
    restart: always
    depends_on:
      - gpl
    container_name: zalgo

  gpl:
    image: gpl
    build: GPL
    ports:
      - 7865:7865
    command: python3 GPL.py
    restart: always
    networks:
      - zalgo_net

    container_name: gpl
networks:
  zalgo_net:
    driver: bridge