version: "3.7"
services:
  server:
    image: zalgo
    build: .
    command: python3 ZalgoBot.py
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - gpl
    container_name: zalgo

# MODULES
  gpl:
    image: gpl
    build: source/modules/GPL
    ports:
      - 7865:7865
    command: python3 GPL.py
    restart: always
    container_name: gpl