# from source.interfaces.AuroraInterface import AuroraInterface
from source.interfaces.ChangeTextModeInterface import ChangeTextModeInterface
from source.interfaces.GPLInterface import GPLInterface
from source.interfaces.ServiceInterface import ServiceInterface
from source.interfaces.SettingsInterface import SettingsInterface
from source.interfaces.ToolsInteface import ToolsInterface
